/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.message;

/**
 * Represents the reason why a message was generated by an agent.
 * 智能体生成消息的原因
 *
 * <p>This enum helps users understand the context and state of agent execution
 * when a message is returned. Different reasons indicate different follow-up
 * actions that may be required.
 *
 * <p>Example usage:
 * <pre>{@code
 * Msg response = agent.call(userMsg).block();
 * switch (response.getGenerateReason()) {
 *     case MODEL_STOP -> System.out.println("Task completed");
 *     case TOOL_SUSPENDED -> handleSuspendedTools(response);
 *     case REASONING_STOP_REQUESTED -> handleHumanReview(response);
 *     // ...
 * }
 * }</pre>
 */
public enum GenerateReason {

    /** Model stopped normally, task completed. */
    // 模型正常停止，任务完成。
    MODEL_STOP,

    /** Model returned tool calls (internal tools, framework will continue execution). */
    // 模型返回工具调用（内部工具，框架将继续执行。）
    TOOL_CALLS,

    /** Structured output completed. */
    // 结构化输出完成。
    STRUCTURED_OUTPUT,

    /** Tool execution was suspended, waiting for user to provide results. */
    // 工具执行被暂停，等待用户提供结果。
    TOOL_SUSPENDED,

    /** Reasoning phase was stopped by a Hook (PostReasoningEvent.stopAgent()). */
    // 推理过程被Hook而停止 类似claude code的 `esc` 指令
    REASONING_STOP_REQUESTED,

    /** Acting phase was stopped by a Hook (PostActingEvent.stopAgent()). */
    // 行为过程被Hook而停止 类似claude code的 `esc` 指令
    ACTING_STOP_REQUESTED,

    /** Agent was interrupted. */
    // 智能体被中断 类似claude code的 `esc` 指令
    INTERRUPTED,

    /** Maximum iterations reached. */
    // 最大迭代次数
    MAX_ITERATIONS
}
