/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.message;

/**
 * Defines the role of a message participant in agent conversations.
 * 消息参与者在智能体对话中的角色
 *
 * <p>This enum specifies the origin or purpose of each message in the conversation
 * flow, enabling proper message routing, processing, and context management.
 *
 * <p>Message roles:
 * <ul>
 *   <li>{@link #USER} - Messages from human users or external inputs</li>
 *   <li>{@link #ASSISTANT} - Messages generated by AI agents or assistants</li>
 *   <li>{@link #SYSTEM} - System instructions, prompts, or configuration messages</li>
 *   <li>{@link #TOOL} - Messages containing tool execution results or responses</li>
 * </ul>
 *
 * <p>The role is essential for determining how messages should be processed
 * and formatted when interacting with different LLM APIs and tool systems.
 */
public enum MsgRole {
    /**
     * User role for messages from human users or external inputs.
     * 用户校色：通过人类或者其他输入
     * <p>These messages typically contain user questions, commands, or input data
     * that the agent needs to process or respond to.
     *  包括用户输入的问题、命令、或者智能体输入的数据
     */
    USER,

    /**
     * Assistant role for messages generated by AI agents or assistants.
     * 智能体角色：通过智能体生成的消息
     *
     * <p>These messages contain the agent's responses, reasoning, or actions
     * in response to user messages or system prompts.
     * 这些消息包含代理的响应、推理或者操作、响应用户消息或者系统提示
     */
    ASSISTANT,

    /**
     * System role for system instructions, prompts, or configuration messages.
     * 系统角色： 系统指令、提示、或者配置消息
     * <p>These messages typically contain setup instructions, context information,
     * or system-level directives that guide agent behavior.
     * 这些消息通常包含设置指令、上下文信息或者系统级别的指令，以指导agent的行为
     */
    SYSTEM,

    /**
     * Tool role for messages containing tool execution results or responses.
     * 工具角色：包含工具执行结果的消息
     *
     * <p>These messages contain the output from tool executions, including
     * return values, error messages, or status information from external tools.
     * 这些消息包含工具执行的输出，包含返回值、错误信息或者外部工具的状态信息
     */
    TOOL
}
